echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching and Merging"
echo "Dnyaneshwar Ramdas Nangrale"
echo "We are learning git and github"